config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  resources :tasks do
    resources :subtasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  validates :title, :description, presence: true
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :description, presence: true
  belongs_to :user
  has_many :subtasks

  accepts_nested_attributes_for :subtasks

  scope :public_tasks, -> { where(private_task: false ) }
  scope :private_tasks, -> { where(private_task: true ) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :tasks
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :js, :html

  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/subtasks_controller.rb
class SubtasksController < BaseController

  def create
    @subtask = Subtask.new subtask_params
    @subtask.task_id = params[:task_id]
    @subtask.save
    respond_with @subtask.task, notice: 'SubTask was successfully created.'
  end

  def destroy
    task = current_user.tasks.find params[:task_id]
    subtask =  task.subtasks.find(params[:id])
    subtask.destroy
    redirect_to task_path(task.id)
  end

  def update
    @task = current_user.tasks.find params[:id]
    @task.update(task_params)
    respond_with @task
  end

  private

  def subtask_params
    params.require(:subtask).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < BaseController

  def index
    @my_tasks = current_user.tasks
    @public_tasks = Task.where(private_task: false).where.not(user_id: current_user.id)
  end

  def new
    @task = Task.new
    respond_with @task
  end

  def create
    @task = Task.new task_params
    @task.user = current_user
    @task.save
    respond_with @task
  end

  def show
    task = Task.find params[:id]
    @subtask = task.subtasks.build
    @subtasks = task.subtasks
    @task = task if (task.user == current_user || !task.private_task)
    respond_with @task
  end

  def edit
    @task = current_user.tasks.find params[:id]
    respond_with @task
  end

  def destroy
    @task = current_user.tasks.find params[:id]
    @task.destroy
    respond_with @task
  end

  def update
    @task = current_user.tasks.find params[:id]
    @task.update(task_params)
    respond_with @task
  end

  private

  def task_params
    params.require(:task).permit(:title, :private, :description, :finished)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= simple_form_for [@task, @subtask] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn-success' %>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :private_task %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Private?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.private_task %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<hr/>

<h1>Another users public tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New task', new_task_path %>

app/views/tasks/new.html.erb
<h1> New Task </h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1> Details </h1>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Private?:</strong>
  <%= @task.private_task %>
</p>


<hr/>

<table>
<h2>Subtasks</h2>
  <% @subtasks.each do |subtask| %>
    <tr>
      <td><%= subtask.title %></td>
      <td><%= subtask.description %></td>
    </tr>
  <% end %>
</table>
<hr/>
<h3> New Subtask </h3>
<%= render 'subtasks/form' %>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>